# Generated by Django 3.2.4 on 2021-06-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
